theme: jekyll-theme-minimal
title: Zhongweijing's Page
description: Urban Planner & GIS Researcher

# 添加导航栏
navigation:
  - name: Home
    link: /index
  - name: About Me
    link: /cv
  - name: Projects
    link: /projects
  - name: Research
    link: /research


baseurl: "/zhongweijing.github.io/docs"  # 如果你的 GitHub Pages 不是根域名，需要加这个
